### ISSUE TITLE
nektar.py create_fmindex gets stuck

### ISSUE THREAD

**Issue by nellykan** [iric-soft/nektar#3]
Hi! 
I tried to use nektar.py create_fmindex but it doesn't seem to work. 
I don’t get any error but it runs forever without producing an output file. 
I also tried python /path/to/nektar.py -h but it also doesn't respond (gets stuck).
 
Do you have any idea what I might be doing wrong? I have loaded all the necessary modules, and I have successfully used the kmer_assembly command before. 
 
Thanks, 
 
Nelly

**Comment by ericloud** [comment]
Hi Nelly, 

Usually when create_fmindex run forever, it's because you need to format your fasta file with a maximum of n bp by line (using FASTA Formatter from FASTX-Toolkit for example or [here](https://www.biostars.org/p/205745/)).

But in your case, the issue seems to be different, as you can't  run  _python /path/to/nektar.py -h_.
I have no idea how python can stay stuck during help display and don't print an error message. 
 - Have you try to run a simple python script ? As:
```
def main():
  print("Hello")

main()
```

 - Also can you copy past the output, when you kill _python /path/to/nektar.py -h_ (using ctrl+c) ?

**Comment by nellykan** [comment]
Thank you for your prompt response!

I have processed my fasta file to contain 70 characters per line, so I think that is not a problem. 
Also, yes simple (and more complex) python scripts seem to work fine. 
 
When killing python /path/to/nektar.py -h I get the following:

```
^CTraceback (most recent call last):
  File "nektar-master/nektar_py/nektar.py", line 7, in <module>
    import tools.create_fmindex as tc
  File "/home/ek249/nektar-master/nektar_py/tools/create_fmindex.py", line 7, in <module>
    folder_fm = os.path.dirname(folder_fm)
  File "/n/app/python/2.7.12/lib/python2.7/posixpath.py", line 124, in dirname
    if head and head != '/'*len(head):
KeyboardInterrupt
```

**Comment by ericloud** [comment]
Ok I have it. 

You need to rename your folder "nektar-master" to "nektar".
Or change the code here: https://github.com/iric-soft/nektar/blob/c5072b6277c072142add58a28bddc2a0664e4dff/nektar_py/tools/create_fmindex.py#L6

Sorry the code isn't robust to allow to change folder's name :).

Regards,
Eric.

**Comment by nellykan** [comment]
Oh yep that was it! Thanks so much!
