### ISSUE TITLE
kmer_assembly doesn't output fasta and tab file.

### ISSUE THREAD

**Issue by yiolino** [iric-soft/nektar#6]
@ericloud 
Thank you for great software.

When I run the kmer_assembly program, it does not output any fasta or tab files and exits in the middle of the program.

```
/nektar/nektar_cpp/kmer_assembly \
            -r \
            -p ${project_file} \
            -k ${outdir}/${ass_name}.assembly \
            -o ${outdir} \
            -l 33
```

After this message, the program is terminated.
```
Read args
Read project
Read kmer
7770041 kmers read
Time : 29.3601
Create graph assembly
```

Removing the -r flag yielded fasta and tab files.
Or, if I reduced the data size a bit (7,600,000 lines), I got the output even with the -r flag.

Is my input file too large?
I can send you sample data if you need it.

**Comment by ericloud** [comment]
Hi @tetsuro90,

As I'm in vacation, this is just a first quick answer, to let you check some points (before to investigate futher):
 1) You sayed that you have test with a reduced data file and it's work fine (with -r flag). Can you try to run kmer_assembly on the second part of your file ? Just to be sure that the bug appear only when we run the full file and not because something in the second part of your file trigger the bug.
  2) Have you check the memory (RAM) usage during the execution of the full file ? Do you reach the limit of your computer ? If it's the case, can you try on a computer with more memory ?
  
 Regards,
 Eric.

**Comment by yiolino** [comment]
@ericloud 
Thank you for your reply.
Sorry to bother you during your vacation.

1.  I tried to run kmer_assembly on the second part, it worked fine.
2. During program execution, RAM memory seemed sufficient. For reference, here are the specs of my computer and the stdout from running kmer_assembly in /usr/bin/time.

Ubuntu 20.04 LTS
64core 128 threads
RAM 256G

```
Read args
Read project
Read kmer
7770041 kmers read
Time : 29.087
Create graph assembly
Command terminated by signal 11
30.04user 0.87system 0:31.04elapsed 99%CPU (0avgtext+0avgdata 3170744maxresident)k
184inputs+0outputs (2major+791960minor)pagefaults 0swaps
```

Regards,

**Comment by jplaverdure** [comment]
Hi @tetsuro90 ,

The only times I've run in similar issues was when I had forgotten to set:  
`ulimit -s unlimited` (as stated in the requirements) prior to launching the assembly.

On larger datasets, the default limits can prove insufficient.

**Comment by yiolino** [comment]
@jplaverdure @ericloud 
It works perfectly !!!
Thank you for sharing your solution.

Sorry I missed the requirement part of the README.
This time I used docker, so I actually resolved it by setting `docker run --ulimit stack=8277716992: 8277716992`

Regards,
Tetsuro

**Comment by ericloud** [comment]
Happy to see that the issue is resolved.
I hope that Nektar will help you in your search.

Regard,
Eric.
